apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-app-role
  namespace: spark-apps
  labels:
    app.kubernetes.io/part-of: spark-platform
    app.kubernetes.io/component: spark-apps
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
